name: Release
'on':
  push:
    branches:
      - alpha
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/semantic-release-workflow/.github/workflows/release.yml@0797071930939acdc001cc9f4e18e4ff3fd57c12 # v2.0.3
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
