name: Release
'on':
  push:
    branches:
      - alpha
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/semantic-release-workflow/.github/workflows/release.yml@dbba19cabb97e923f5eb8b7437e867093bb3bdf7 # v2.0.2
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
