name: Release
'on':
  push:
    branches:
      - alpha
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/semantic-release-workflow/.github/workflows/release.yml@3dee956b9df0269d455344fbdfa789a78a5d4a9b # v2.1.0
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
