name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 18.19.0
          - 20.6.1
          - 22.0.0
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm clean-install
      - run: npm test
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm test
      - uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
  release:
    needs:
      - verify
      - verify-matrix
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
permissions:
  contents: read
